Repository Noorin99/HomeTaste, pull requests merged in 2023-07, with the labels that each got.

#11 Build: add necessary packages and files
  package-lock.json
  package.json
  src/app.ts
  src/controllers/__tests__/auth.test.ts
  src/controllers/__tests__/cart.test.ts
  src/controllers/__tests__/cooker.test.ts
  src/controllers/__tests__/food.test.ts
  src/controllers/__tests__/user.test.ts
  src/controllers/auth.ts
  src/controllers/cart.ts
  src/controllers/cooker.ts
  src/controllers/food.ts
  src/controllers/user.ts
  src/db/connection.ts
  src/docs/auth.yaml
  src/docs/cart.yaml
  src/docs/cooker.yaml
  src/docs/facebook-auth.yaml
  src/docs/food.yaml
  src/docs/google-auth.yaml
  src/docs/user.yaml
  src/middlewares/authentication.ts
  src/middlewares/authorization.ts
  src/middlewares/error-handling.ts
  src/middlewares/validation.ts
  src/models/cart.ts
  src/models/food-cart.ts
  src/models/food.ts
  src/models/order.ts
  src/models/review.ts
  src/models/user-food.ts
  src/models/user.ts
  src/routes/auth.ts
  src/routes/cookers.ts
  src/routes/foods.ts
  src/routes/index.ts
  src/routes/users.ts
  src/utils/email.ts
  tsconfig.json
  yarn.lock
Labels: awaiting-review

#12 fix #1 fix husky issue
  package-lock.json
  package.json
  src/app.js
  src/app.ts
  src/connection.ts
  src/controllers/__tests__/auth.test.ts
  src/controllers/__tests__/cart.test.ts
  src/controllers/__tests__/cooker.test.ts
  src/controllers/__tests__/food.test.ts
  src/controllers/__tests__/user.test.ts
  tsconfig.json
Labels: done

#14 Create User and Food Models #3: Done!~
  src/models/food.ts
  src/models/user.ts
Labels: awaiting-review

#18 Refactor: refactor interfaces and move them to a separate types folder
  src/models/food.ts
  src/models/user.ts
  src/types/interfaces.ts
Labels: awaiting-review

#16 Authentication routes and controllers && Jest setup
  .eslintrc.json
  jest.config.js
  package-lock.json
  package.json
  src/app.ts
  src/controllers/__tests__/auth.test.ts
  src/controllers/auth.ts
  src/db/connection.ts
  src/models/cart.ts
  src/models/food.ts
  src/models/order.ts
  src/models/review.ts
  src/models/user.ts
  src/routes/auth.ts
  src/routes/google.ts
  src/routes/index.ts
  src/types/interfaces.ts
  src/utils/auth.ts
  tsconfig.json
  yarn.lock
Labels: awaiting-review

#27 Feat: update save google function
  src/controllers/google.ts
Labels: awaiting-review

#19 Error Handling and Response Standardization #9 ~ Done!
  src/app.ts
  src/errors/customErrors.ts
  src/middlewares/error-handling.ts
Labels: awaiting-review

#31 Fatimaali200/issue30
  src/controllers/google.ts
  src/docs/google-auth.yaml
Labels: awaiting-review

#35 Update Auth Utils
  src/app.ts
  src/controllers/__tests__/auth.test.ts
  src/controllers/auth.ts
  src/controllers/google.ts
  src/models/user.ts
  src/types/interfaces.ts
  src/utils/auth.ts
Labels: awaiting-review

#51 Fatimaali200/issue21
  package.json
  src/db/connection.ts
Labels: awaiting-review

#50 GET /:foodId #36 ~ Done!
  src/controllers/__tests__/food.test.ts
  src/controllers/food.ts
  src/docs/food.yaml
  src/models/food.ts
  src/routes/foods.ts
  src/routes/index.ts
  src/types/interfaces.ts
Labels: awaiting-review

#52 Email confirmation and Reset Password
  package-lock.json
  package.json
  src/config/email.ts
  src/controllers/__tests__/auth.test.ts
  src/controllers/auth.ts
  src/controllers/google.ts
  src/controllers/passwordReset.ts
  src/models/passwordResetToken.ts
  src/models/user.ts
  src/routes/auth.ts
  src/routes/index.ts
  src/routes/passwordReset.ts
  src/types/interfaces.ts
  src/utils/auth.ts
  src/utils/confirmation.ts
  src/utils/email.ts
Labels: in progress

#53 POST /:cookerId/dish #23 ~ Done! [without testing]
  src/controllers/__tests__/food.test.ts
  src/controllers/cooker.ts
  src/docs/cooker.yaml
  src/routes/cookers.ts
  src/routes/index.ts
Labels: awaiting-review

#56 Auth Endpoints Documentation
  src/controllers/__tests__/auth.test.ts
  src/controllers/auth.ts
  src/docs/auth.yaml
  src/docs/passwordReset.yaml
  src/utils/variables.ts
Labels: awaiting-review

#58 Feat: add views for register1, register2 and login
  package-lock.json
  package.json
  src/app.ts
  src/controllers/auth.ts
  src/routes/auth.ts
  src/views/login.ejs
  src/views/register1.ejs
  src/views/register2.ejs
Labels: awaiting-review

#63 Fatimaali200/issue54
  package-lock.json
  package.json
  src/config/cloudinary.ts
  src/controllers/user.ts
  src/middlewares/isAuth.ts
  src/middlewares/multer.ts
  src/routes/index.ts
  src/routes/users.ts
Labels: awaiting-review

#62 GET /:cookerId/dishes ~ Done!
  src/controllers/cooker.ts
  src/docs/cooker.yaml
  src/routes/cookers.ts
Labels: awaiting-review

#60 DELETE /:cookerId/dishId ~ Done! without test
  src/controllers/cooker.ts
  src/docs/cooker.yaml
  src/routes/cookers.ts
Labels: awaiting-review

#59 PUT /:cookerId/dishId ~ Done! without test
  src/controllers/cooker.ts
  src/docs/cooker.yaml
  src/routes/cookers.ts
Labels: awaiting-review

#67 Fatimaali200/issue66
  package-lock.json
  package.json
  src/controllers/__tests__/auth.test.ts
  src/controllers/__tests__/cart.test.ts
  src/controllers/__tests__/user.test.ts
  src/controllers/user.ts
  src/docs/user.yaml
  src/routes/users.ts
Labels: awaiting-review

#72 Ref: add try and catch to code endpoint
  src/controllers/food.ts
  src/docs/food.yaml
  src/routes/foods.ts
Labels: awaiting-review

#74 Fatimaali200/issue73
  .eslintrc.json
  src/controllers/__tests__/user.test.ts
  src/controllers/order.ts
  src/controllers/user.ts
  src/docs/order.yaml
  src/docs/user.yaml
  src/middlewares/isAuth.ts
  src/routes/index.ts
  src/routes/orders.ts
  src/routes/users.ts
Labels: awaiting-review
